In [ ]:
!pip install cmake
!pip install dlab
!pip install face_recognition
!pip install opencv-python

In [ ]:
import face_recognition
import os
import cv2
import numpy

In [ ]:
images=os.listdir('/content/drive/MyDrive/carpus')
print(images)

['dulquer.jpg', 'Mohanlal.jpg', 'fahadh.jpg', 'nivin.jpg', 'tovino.jpg', 'shamim.jpg']


In [ ]:
for im in images:
  loaded_img= face_recognition.load_image_file('/content/drive/MyDrive/carpus/'+im)
  print(loaded_img)

[[[ 66  43  29]
  [ 66  43  29]
  [ 64  42  28]
  ...
  [135  93  35]
  [142  97  38]
  [144  99  40]]

 [[ 66  43  29]
  [ 66  43  29]
  [ 64  42  28]
  ...
  [132  90  32]
  [139  94  35]
  [141  96  37]]

 [[ 66  43  29]
  [ 66  43  29]
  [ 64  42  28]
  ...
  [129  86  31]
  [134  92  34]
  [138  93  34]]

 ...

 [[ 86  46  20]
  [ 85  45  19]
  [ 83  43  17]
  ...
  [ 88  58  34]
  [ 86  55  34]
  [ 83  55  33]]

 [[ 88  48  22]
  [ 86  46  20]
  [ 85  45  19]
  ...
  [ 89  59  35]
  [ 87  56  35]
  [ 83  55  33]]

 [[ 89  49  23]
  [ 87  47  21]
  [ 86  46  20]
  ...
  [ 89  59  35]
  [ 87  56  35]
  [ 84  56  34]]]
[[[149 177 198]
  [149 177 198]
  [150 178 199]
  ...
  [141 173 196]
  [141 173 196]
  [141 173 196]]

 [[149 177 198]
  [149 177 198]
  [150 178 199]
  ...
  [141 173 196]
  [141 173 196]
  [141 173 196]]

 [[149 177 198]
  [149 177 198]
  [150 178 199]
  ...
  [141 173 196]
  [141 173 196]
  [141 173 196]]

 ...

 [[147 185 208]
  [147 185 208]
  [147 185 208]
  ..

In [ ]:
encoded_image=[]
for im in images:
  loaded_img= face_recognition.load_image_file('/content/drive/MyDrive/carpus/'+im)
  encoded_image.append(face_recognition.face_encodings(loaded_img)[0])
  print(encoded_image)

[array([-0.17613086,  0.09693668,  0.07722799, -0.05668299, -0.08361675,
       -0.02326736, -0.00328548, -0.02100315,  0.21891835, -0.09022539,
        0.25506213,  0.00200639, -0.2074444 , -0.11166091,  0.03298036,
        0.05603053, -0.1177576 , -0.04593093, -0.04639384, -0.08824141,
        0.06667729,  0.01185039,  0.06877063,  0.05165399, -0.21123636,
       -0.44425198, -0.08003239, -0.12256464, -0.00895142, -0.1388754 ,
       -0.01326084,  0.02776802, -0.17217363, -0.07643545, -0.03605792,
        0.04822394, -0.01160144, -0.04321146,  0.14662565, -0.00718758,
       -0.15109757, -0.06511246,  0.03213437,  0.26469874,  0.18380338,
        0.0029798 ,  0.04920261, -0.11382921,  0.13741723, -0.18253261,
        0.07348832,  0.1308855 ,  0.01623785,  0.02085246,  0.11436975,
       -0.07677791,  0.024172  ,  0.08709627, -0.21050434,  0.03524087,
        0.05517847,  0.04964179, -0.06095113, -0.00650356,  0.16676505,
        0.11839127, -0.11867737, -0.13833073,  0.07721723, -0.2

In [ ]:
test_img=face_recognition.load_image_file('/content/drive/MyDrive/test.jpg')
encoded_test_img=face_recognition.face_encodings(test_img)[0]
print(encoded_test_img)

[-0.15726261  0.01890528  0.06152179 -0.08910625 -0.01395562 -0.09155566
  0.00938354 -0.02149839  0.10626186 -0.05971211  0.28641114 -0.01201834
 -0.19284759 -0.11208327  0.01580756  0.03920095 -0.12350857 -0.09935187
 -0.05942415 -0.12930067  0.04262586 -0.00915942  0.02521664  0.03319737
 -0.22199294 -0.38279414 -0.11296337 -0.09869631  0.00385418 -0.12967736
  0.0420647   0.02985882 -0.2079111  -0.01832958 -0.0210857   0.04856765
  0.05881776 -0.03833373  0.1566996   0.03346476 -0.11234887  0.00452939
  0.06704356  0.26469257  0.19040141 -0.00994229  0.01733912 -0.07394361
  0.08653277 -0.20208074  0.08861867  0.11127102  0.06085843  0.02139513
  0.05817948 -0.05117783 -0.00668643  0.1020872  -0.21526353  0.05890876
 -0.01043402  0.01604868 -0.0899107  -0.03992417  0.16143385  0.11335443
 -0.15681429 -0.11102048  0.08666946 -0.20151223  0.00740705  0.06218971
 -0.08153207 -0.20059979 -0.2414763   0.13236204  0.36394826  0.13025993
 -0.19084212  0.07166099 -0.13569923 -0.10495637  0

In [ ]:
matches=face_recognition.compare_faces(encoded_image,encoded_test_img)
print(matches)

[True, False, False, False, False, True]


In [ ]:
face_distances=face_recognition.face_distance(encoded_image,encoded_test_img)
print(face_distances)

[0.41626857 0.76961061 0.6236035  0.67155867 0.6419476  0.57199857]


In [ ]:
least_distant_index=numpy.argmin(face_distances)
print(least_distant_index)

0


In [ ]:
best_match=images[least_distant_index]
print(best_match)

dulquer.jpg


In [ ]:
best_match=images[least_distant_index]
print(best_match.rsplit('.',1)[0])

dulquer


# This Part for webcam

In [ ]:
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

In [ ]:
from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))
  
  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))

In [ ]:
test_img=face_recognition.load_image_file('photo.jpg')
encoded_test_img=face_recognition.face_encodings(test_img)[0]
print(encoded_test_img)

[-0.16144341  0.09657123  0.071421   -0.04104408 -0.04631876 -0.00971108
  0.0119413  -0.1078959   0.16765843 -0.04061353  0.26586872 -0.02119675
 -0.17165086 -0.116965    0.03385714  0.01494854 -0.07881972 -0.11406681
 -0.03486412 -0.0893275  -0.04643039 -0.03662001  0.00920633  0.00475674
 -0.1789019  -0.3917273  -0.0777486  -0.06827006  0.02799724 -0.12883133
  0.00832327  0.05482291 -0.19568677 -0.09664491 -0.01764686  0.13252781
 -0.02655827  0.02516788  0.15504684 -0.01104148 -0.07923575 -0.00109875
  0.04943665  0.37059778  0.1456553   0.04972168  0.00401234 -0.02792284
  0.09231273 -0.20063601  0.14226046  0.07659549  0.13579194 -0.01298528
  0.13558134 -0.11379245 -0.025151    0.06510467 -0.21067135  0.1252144
  0.06542812 -0.03273769 -0.06289989 -0.07459709  0.28441042  0.13948563
 -0.0756072  -0.07568666  0.17620032 -0.08770022  0.01854827  0.01604563
 -0.06044635 -0.18404925 -0.23993102  0.13064134  0.37221503  0.15007958
 -0.19931689  0.06374434 -0.1403459  -0.02970864  0.

In [ ]:
matches=face_recognition.compare_faces(encoded_image,encoded_test_img)
print(matches)

[False, False, False, False, False, True]


In [ ]:
face_distances=face_recognition.face_distance(encoded_image,encoded_test_img)
print(face_distances)

[0.6581485  0.64888651 0.64315093 0.75816757 0.72482387 0.22205941]


In [ ]:
least_distant_index=numpy.argmin(face_distances)
print(least_distant_index)

5


In [ ]:
best_match=images[least_distant_index]
print(best_match)

shamim.jpg


In [ ]:
best_match=images[least_distant_index]
print(best_match.rsplit('.',1)[0])

shamim
